files:
  - source: /L10n/en.template.strings
    translation: /L10n/%two_letters_code%.strings

  - source: /data/colonisation_legend.txt
    translation: /data/L10n/%two_letters_code%.colonisation_legend.txt
    file_type: text

  - source: /data/commodity.csv
    translation: /data/L10n/%two_letters_code%.commodity.csv
    file_type: csv

  - source: /data/rare_commodity.csv
    translation: /data/L10n/%two_letters_code%.rare_commodity.csv
    file_type: csv
